name: country_code_conversion
description: A project to convert country codes to country names and vice versa.
version: 1.0.4
homepage: https://github.com/CuongNVTN/country_code_conversion

environment:
  sdk: ">=2.12.0 <3.0.0"